spring:
  datasource:
    hikari:
      url: jdbc:h2:tcp://localhost/~/kakaobank
      driver-class-name: org.h2.Driver
      username: sa
  h2:
    console:
      path: /h2console
      enabled: true
  redis:
    host: localhost
    port: 6379
    timeout: 2000
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

api:
  kakaobank:
    api-key: a77d0a1e2de3b7d8365b27f71ff809af
    url: https://dapi.kakao.com/v2/search/
  naver:
    client-id: v4pyFwZIqBLjXnPHDlZC
    client-secret: ooC5Bc8LkQ
    url: https://openapi.naver.com/v1/search/
